---
- name: Check for haproxy_rke2_servers
  ansible.builtin.fail:
    msg: "The variable 'haproxy_rke2_servers' is not defined"
  when: haproxy_rke2_servers is not defined

- debug: 
    msg: "haproxy_rke2_servers = {{ haproxy_rke2_servers }}"
  when: haproxy_rke2_debug | default(false) | bool

- block:
  - name: Update package cache (Debian)
    ansible.builtin.apt:
      update_cache: true
    when: ansible_os_family == 'Debian'

  - name: Update package cache (RedHat)
    ansible.builtin.yum:
      name: '*'
      state: latest
      update_cache: true
    when: ansible_os_family == 'RedHat'

  - name: Install haproxy
    ansible.builtin.package:
      name: haproxy
      state: "{{ 'latest' if haproxy_rke2_action == 'upgrade' else 'present' }}"
    notify: restart haproxy

  - name: Write haproxy.cfg 
    ansible.builtin.template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: 0644
    notify: restart haproxy
  become: true

# run restart haproxy now
- meta: flush_handlers