---
- name: Install haproxy_rke2 
  include_tasks: install.yaml 
  when: haproxy_rke2_action in ['install', 'upgrade']

- name: Remove haproxy_rke2
  include_tasks: teardown.yaml
  when: haproxy_rke2_action == 'teardown'