---
- name: Install HAProxy 
  include_tasks: install.yaml 
  when: haproxy_rke2_action in ['install', 'upgrade']

- name: Remove HAProxy
  include_tasks: teardown.yaml
  when: haproxy_rke2_action == 'teardown'