---
on:
  pull_request:
    types:
      - opened
      - synchronize
  #schedule:
  #  - cron: '20 5 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        MOLECULE_DISTRO:
          - centos7
          - rockylinux8
          - rockylinux9
          - ubuntu2204
          - ubuntu2004
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: molecule
        uses: robertdebock/molecule-action@5.0.1
        env:
          MOLECULE_DISTRO: ${{ matrix.MOLECULE_DISTRO }}
